kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ks-gradle:local
    commands:
      - gradle --no-daemon build uploadArchives

  - name: local-release
    image: ks-local-maven-dist:local
    commands:
      - dist build/maven/*

  - name: publish-release
    image: ks-gradle:local
    commands:
      - gradle -Drelease=true uploadArchives
    when:
      ref:
        - refs/tags/*